"""add_workout_request_and_workflow_state_tables

Revision ID: 1b4e0151db54
Revises: 2a9fce9b3d11
Create Date: 2026-03-04 16:27:05.414511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4e0151db54'
down_revision: Union[str, None] = '2a9fce9b3d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONTEXT_READY', 'DRAFT_READY', 'PARTIAL_READY', 'COMPLETED', 'FAILED', name='workout_request_status'), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saga_id', name='uq_saga_id')
    )
    op.create_index(op.f('ix_workout_requests_id'), 'workout_requests', ['id'], unique=False)
    op.create_index(op.f('ix_workout_requests_saga_id'), 'workout_requests', ['saga_id'], unique=False)
    op.create_table('workflow_state',
    sa.Column('saga_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('exercises_ready', sa.Boolean(), nullable=True),
    sa.Column('playlist_ready', sa.Boolean(), nullable=True),
    sa.Column('exercises_event_id', sa.UUID(), nullable=True),
    sa.Column('playlist_event_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['workout_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('saga_id')
    )
    op.create_index(op.f('ix_workflow_state_saga_id'), 'workflow_state', ['saga_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_state_saga_id'), table_name='workflow_state')
    op.drop_table('workflow_state')
    op.drop_index(op.f('ix_workout_requests_saga_id'), table_name='workout_requests')
    op.drop_index(op.f('ix_workout_requests_id'), table_name='workout_requests')
    op.drop_table('workout_requests')
    # ### end Alembic commands ###
