"""update workout schema

Revision ID: 4fecaf1d1558
Revises: b0f9e987f21d
Create Date: 2025-10-27 09:09:16.404996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fecaf1d1558'
down_revision: Union[str, None] = 'b0f9e987f21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('playlist_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'playlist_url')
    # ### end Alembic commands ###
