"""add top_artists and top_tracks to preferences

Revision ID: 81669b0aa16a
Revises: adcf99a85292
Create Date: 2025-11-15 18:54:21.179471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81669b0aa16a'
down_revision: Union[str, None] = 'adcf99a85292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('top_artists', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('preferences', sa.Column('top_tracks', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'top_tracks')
    op.drop_column('preferences', 'top_artists')
    # ### end Alembic commands ###
