"""add spotify_user_id to users table

Revision ID: adcf99a85292
Revises: 4fecaf1d1558
Create Date: 2025-11-15 17:08:28.991487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adcf99a85292'
down_revision: Union[str, None] = '4fecaf1d1558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_spotify_user_id'), 'users', ['spotify_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_spotify_user_id'), table_name='users')
    op.drop_column('users', 'spotify_user_id')
    # ### end Alembic commands ###
